### ISSUE TITLE
SPA vs MPA

### ISSUE THREAD

**Issue by TerryJoo** [asdf-team/remember-me#1]
svelte SPA에서 조금 아쉬운 점
- angular나 react처럼 개발 환경에서 404 처리를 깔끔하게 해주지 않음(루트 페이지 외의 페이지를 url로 접속하거나, 새로고침 시, 404가 보임)

결정 시 고려할 내용
1. SPA의 아쉬운 점은 실제 배포시엔 해결될 문제(개발 시에만 불편할 수 있음)
2. 정말로 클라이언트 사이드 Router가 필요한가(이번 버전에서 Router 자체가 필요하지 않을 수 있기 때문에 큰 문제가 아닐 수 있음)
3. 서버 비용(MPA로 개발 시, EC2 같은 인스턴스 형태로 올리는 게 편함 = 비쌈 => Cloud 서비스 별 설정에 따라 SPA처럼 고정 지출을 낮출 순 있어보임)

**Comment by TerryJoo** [comment]
의견 주세요~

**Comment by cn3085** [comment]
wow... 정말 빠르다

**Comment by TerryJoo** [comment]
지난 주 SPA로 결정되었으니 이슈를 닫겠습니다.
